services:
    laravel.test:
        build:
            context: './docker/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        restart: unless-stopped
        depends_on:
            - mysql
            - redis
            - minio
            - mailpit
            
    mysql:
        image: mysql:lts
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
            - MYSQL_DATABASE=${DB_DATABASE:-laravel}
            - MYSQL_USER=${DB_USERNAME:-sail}
            - MYSQL_PASSWORD=${DB_PASSWORD:-password}
            - MAUTIC_DB_DATABASE=${MAUTIC_DB_DATABASE:-mautic}
        volumes:
            - './.docker/mysql:/var/lib/mysql'
            - './docker/mysql/init-databases.sh:/docker-entrypoint-initdb.d/10-init-databases.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 10
        restart: unless-stopped
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - '${FORWARD_PHPMYADMIN_PORT:-8080}:80'
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=${DB_USERNAME:-sail}
            - PMA_PASSWORD=${DB_PASSWORD:-password}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
            - UPLOAD_LIMIT=300M
            - PMA_ARBITRARY=1
            - PMA_ABSOLUTE_URI=http://localhost:${FORWARD_PHPMYADMIN_PORT:-8080}/
        # volumes:
        #     - './.docker/phpmyadmin:/etc/phpmyadmin'
        networks:
            - sail
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - './.docker/redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
        restart: unless-stopped
    
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
        restart: unless-stopped
    minio:
        image: minio/minio:latest
        entrypoint: /bin/sh -c
        command: |
            "
            minio server /data --console-address ':8900' &

            sleep 5

            mc alias set myminio http://localhost:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY}

            mc mb -p myminio/${AWS_BUCKET}

            mc anonymous set public myminio/${AWS_BUCKET}

            wait
            "
        ports:
            - "${FORWARD_MINIO_PORT:-9000}:9000"
            - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
        environment:
            MINIO_ROOT_USER: "${AWS_ACCESS_KEY_ID}"
            MINIO_ROOT_PASSWORD: "${AWS_SECRET_ACCESS_KEY}"
            AWS_BUCKET: "${AWS_BUCKET}"
        volumes:
            - './.docker/minio:/data'
        networks:
            - sail
        restart: unless-stopped
    
    stripe-cli:
        image: stripe/stripe-cli:latest
        container_name: stripe-cli
        entrypoint: /bin/sh
        command: >
            -c "
            sleep 10 &&
            stripe listen 
            --forward-to http://laravel.test/stripe/webhook 
            --api-key $${STRIPE_SECRET}
            --skip-verify
            "
        environment:
            STRIPE_API_KEY: "${STRIPE_SECRET}"
        volumes:
            - './.docker/stripe:/root/.config/stripe'
        networks:
            - sail
        restart: unless-stopped
        depends_on:
            laravel.test:
                condition: service_started

    mautic_web:
        image: mautic/mautic:latest
        ports:
            - '${FORWARD_MAUTIC_PORT:-1111}:80'
        volumes:
            - './.docker/mautic/config:/var/www/html/config:z'
            - './.docker/mautic/logs:/var/www/html/var/logs:z'
            - './.docker/mautic/media/files:/var/www/html/docroot/media/files:z'
            - './.docker/mautic/media/images:/var/www/html/docroot/media/images:z'
            # - './.docker/mautic/cron:/opt/mautic/cron:z # Uncomment this line to customize your cron configuration
        environment:
            - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA:-false}
            - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS:-true}
        env_file:
            - docker/mautic/.env
        networks:
            - sail
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 100
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
    
    mautic_cron:
        image: mautic/mautic:latest
        volumes:
            - './.docker/mautic/config:/var/www/html/config:z'
            - './.docker/mautic/logs:/var/www/html/var/logs:z'
            - './.docker/mautic/media/files:/var/www/html/docroot/media/files:z'
            - './.docker/mautic/media/images:/var/www/html/docroot/media/images:z'
            # - './.docker/mautic/cron:/opt/mautic/cron:z # Uncomment this line to customize your cron configuration
        environment:
            - DOCKER_MAUTIC_ROLE=mautic_cron
        env_file:
            - docker/mautic/.env
        networks:
            - sail
        restart: unless-stopped
        depends_on:
            mautic_web:
                condition: service_healthy
    
    mautic_worker:
        image: mautic/mautic:latest
        volumes:
            - './.docker/mautic/config:/var/www/html/config:z'
            - './.docker/mautic/logs:/var/www/html/var/logs:z'
            - './.docker/mautic/media/files:/var/www/html/docroot/media/files:z'
            - './.docker/mautic/media/images:/var/www/html/docroot/media/images:z'
            # - './.docker/mautic/cron:/opt/mautic/cron:z # Uncomment this line to customize your cron configuration
        environment:
            - DOCKER_MAUTIC_ROLE=mautic_worker
        env_file:
            - docker/mautic/.env
        networks:
            - sail
        restart: unless-stopped
        depends_on:
            mautic_web:
                condition: service_healthy

networks:
    sail:
        driver: bridge
